theme: jekyll-theme-cayman
title: Tony Luu
description: I'm a Computer Games Development graduate from University of East London with a passion for games development and programming.\n This portfolio demonstrates a variety of gameplay features implemented in these projects to generate interesting gameplay.
github:
  is_project_page: false
